# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://gudepeng.github.io/note/
date_format: "ordinal"
title: 金角大王的note
subtitle: "记录成为架构师道路上的点滴"
description: "金角大王的个人博客"
keywords: 码志, Zhuang Ma, mzlogin, mazhuang
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 金角大王
organization: 
organization_url: 
github_username: gudepeng
location: DaLian, China
email: gudepeng@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href:
    label: 首页

  -
    href: /categories
    label: 分类

  -
     href: /archives
     label: 归档

  -
    href: /wiki
    label: 维基

  -
    href: /links
    label: 链接

  -
    href: /about
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: gudepeng
    repo: note
    clientID: 660e7c91a01fdf9d82a5
    clientSecret: 3a8947c0a6b9acd23c6df98889512dda2534780f
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
